services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: acme_backend
    restart: always
    environment:
      # Variables for Laravel
      APP_ENV: production
      APP_DEBUG: 'false'
      APP_KEY: ${APP_KEY}
      # Connexion to PostgreSQL
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - acme_network

  db:
    image: postgres:15
    container_name: acme_postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - acme_network

networks:
  acme_network:

volumes:
  db_data:
